# Generated by Django 3.1.2 on 2022-10-13 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fare_type',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='business_fare',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depart_day',
            field=models.ManyToManyField(default=None, related_name='flights_of_the_day', to='flight.Week'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depart_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flight.place'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='economy_fare',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='first_fare',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flight.place'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=None)),
                ('departure_time', models.TimeField(default=None)),
                ('arrival_date', models.DateField(default=None)),
                ('arrival_time', models.TimeField(default=None)),
                ('mk_carrier_code', models.CharField(default=None, max_length=64)),
                ('op_carrier_code', models.CharField(default=None, max_length=64)),
                ('numberOfStops', models.CharField(default=None, max_length=64)),
                ('duration', models.CharField(default=None, max_length=64)),
                ('aircraft', models.CharField(default=None, max_length=64)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_arrivals', to='flight.place')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_departures', to='flight.place')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='segments',
            field=models.ManyToManyField(default=None, to='flight.Segment'),
        ),
    ]
