# Generated by Django 3.1.2 on 2022-10-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20221013_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='segment',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
