# Generated by Django 3.1.2 on 2022-10-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_auto_20221013_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='depart_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
