# Generated by Django 3.1.2 on 2022-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_auto_20221013_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depart_day',
            field=models.ManyToManyField(default=None, null=True, related_name='flights_of_the_day', to='flight.Week'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='fare_type',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.CharField(default=None, max_length=24, null=True),
        ),
    ]
