# Generated by Django 3.1.2 on 2022-10-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_auto_20221013_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='depart_day',
        ),
    ]
