# Generated by Django 3.1.2 on 2022-10-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20221013_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price_base',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_currency',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='price_grandTotal',
            field=models.FloatField(default=None, null=True),
        ),
    ]
