# Generated by Django 3.1.2 on 2022-10-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0009_auto_20221013_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price_grandTotal',
            new_name='price_grand_total',
        ),
    ]
