# Generated by Django 3.1.2 on 2022-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0010_auto_20221013_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='seg_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
