# Generated by Django 3.1.2 on 2022-10-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0012_auto_20221013_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='seg_id',
            new_name='segid',
        ),
    ]
