# Generated by Django 3.1.2 on 2022-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0014_auto_20221013_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
